import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';

/* TEC ABOUT — Bold Industrial / International-grade. */

export const metadata: Metadata = { title: 'About TEC INDUSTRIES — Industrial Piping Partner in Vapi, Gujarat', description: 'TEC INDUSTRIES is a Vapi-based B2B industrial piping partner supporting manufacturing plants and industrial projects with product systems, technical resources and project-led enquiry support.', alternates: { canonical: '/about' } };

const VALUES = [
  { letter: 'T', title: 'Trust', body: 'Clear product-family conversations, transparent documentation routes and direct project communication.' },
  { letter: 'E', title: 'Empowerment', body: 'Useful technical resources and enquiry inputs that help procurement, maintenance and project teams begin with the right context.' },
  { letter: 'C', title: 'Commitment', body: 'A long-term industrial-partner mindset—focused on helping projects move from early requirement to useful next action.' },
];

export default function AboutPage() {
  return <div className="bg-[#f3f5f2]"><section className="relative overflow-hidden bg-[#090f14] text-white"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(85,202,146,0.1)_1px,transparent_1px),linear-gradient(90deg,rgba(85,202,146,0.1)_1px,transparent_1px)] [background-size:56px_56px]" /><div className="container-xl relative z-10 grid gap-12 py-[clamp(5rem,10vw,9rem)] lg:grid-cols-[1fr_0.8fr] lg:items-end"><div><p className="section-eyebrow text-[#55ca92]">About TEC INDUSTRIES</p><h1 className="mt-5 max-w-[10ch] font-[var(--font-display)] text-[clamp(4rem,8vw,8rem)] font-extrabold uppercase leading-[0.79] tracking-[-0.055em]">Your partner in industrial progress.</h1></div><p className="max-w-lg text-[1rem] leading-7 text-white/67">TEC INDUSTRIES is based in Vapi, Gujarat and positioned as an industrial piping partner for manufacturing plants and industrial projects—across product systems, technical resources and project-led enquiry support.</p></div></section>
    <section className="section-space bg-white"><div className="container-xl grid gap-12 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><div><p className="section-eyebrow">The operating idea</p><h2 className="section-heading">A piping conversation should start with the project, not the price.</h2><p className="mt-7 max-w-md text-[0.98rem] leading-7 text-[#607384]">TEC works with manufacturing, chemical and pharma, textile, food and beverage, engineering, contracting and plant-maintenance teams. The focus is practical: identify the application, product family and technical context before moving into documents and quotation.</p><Link href="/contact" className="btn-ghost mt-8">Start a project conversation <ArrowUpRight size={16} /></Link></div><div className="relative overflow-hidden bg-[#0f171f] p-3"><div className="relative aspect-[3/2]"><Image src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663160765145/CPtvApVhaKXyigNp.jpg" alt="Industrial piping installation environment" fill sizes="(min-width: 1024px) 55vw, 100vw" className="object-cover" /><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(9,15,20,0.58),transparent)]" /></div><div className="absolute bottom-0 left-0 bg-[#173c36] px-5 py-4"><p className="font-[var(--font-mono)] text-[0.57rem] uppercase tracking-[0.12em] text-[#55ca92]">Based in Vapi, Gujarat</p><p className="mt-1 text-sm text-white/75">Industrial piping solutions for projects and plants.</p></div></div></div></section>
    <section className="bg-[#0f171f] py-[clamp(4.5rem,8vw,8rem)] text-white"><div className="container-xl"><div className="max-w-2xl"><p className="section-eyebrow text-[#55ca92]">Core values</p><h2 className="font-[var(--font-display)] text-[clamp(3rem,5vw,5.5rem)] font-extrabold uppercase leading-[0.82] tracking-[-0.045em]">Built on trust. Driven by commitment.</h2></div><div className="mt-10 grid gap-px border border-white/12 bg-white/12 md:grid-cols-3">{VALUES.map((value) => <div key={value.letter} className="min-h-[21rem] bg-[#0f171f] p-7"><span className="font-[var(--font-display)] text-[5.5rem] font-bold leading-none text-[#55ca92]">{value.letter}</span><h3 className="mt-10 font-[var(--font-display)] text-[2.4rem] font-bold uppercase leading-[0.85]">{value.title}</h3><p className="mt-5 text-sm leading-6 text-white/65">{value.body}</p></div>)}</div></div></section>
    <section className="bg-[#173c36] py-8 text-white"><div className="container-xl flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="font-[var(--font-mono)] text-[0.62rem] uppercase tracking-[0.13em] text-[#55ca92]">For procurement, project and maintenance teams</p><h2 className="mt-2 font-[var(--font-display)] text-[2rem] font-bold uppercase leading-[0.9]">Tell TEC what your system needs to do.</h2></div><Link href="/resources" className="btn-secondary shrink-0">Explore technical resources <ArrowUpRight size={16} /></Link></div></section>
  </div>;
}
