import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight, FileText, FolderOpen, Wrench } from 'lucide-react';

/* TEC RESOURCES — Bold Industrial / International-grade. */

export const metadata: Metadata = { title: 'Technical Resources, Catalogs & Project Documents', description: 'Request technical catalogs, product specifications, installation discussions, and engineering documents for TEC INDUSTRIES piping systems.', alternates: { canonical: '/resources' } };

const RESOURCES = [
  { number: '01', title: 'PPR Catalogue', body: 'Browse TEC’s PPR pipe and fitting-family index, then request current project-specific literature.', href: '/resources/ppr-catalog', action: 'Browse PPR catalogue', icon: FolderOpen },
  { number: '02', title: 'Fusion Guidance', body: 'Request the applicable heat-fusion discussion for pipe system, size range, equipment and installation scope.', href: '/contact?resource=fusion-welding-guide', action: 'Request fusion guidance', icon: Wrench },
  { number: '03', title: 'Compatibility Review', body: 'Share the process medium, concentration, temperature and operating context for a suitable document request.', href: '/contact?resource=chemical-compatibility-review', action: 'Request a review', icon: FileText },
  { number: '04', title: 'Engineering Documents', body: 'Request drawings or engineering support with the product family, nominal size, application and project stage.', href: '/contact?resource=engineering-documents', action: 'Contact engineering', icon: FileText },
];

export default function ResourcesPage() {
  return <div className="min-h-screen bg-[#f3f5f2]">
    <section className="relative overflow-hidden bg-[#090f14] py-[clamp(5rem,10vw,9rem)] text-white"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(85,202,146,0.1)_1px,transparent_1px),linear-gradient(90deg,rgba(85,202,146,0.1)_1px,transparent_1px)] [background-size:56px_56px]" /><div className="container-xl relative z-10 grid gap-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-end"><div><p className="section-eyebrow text-[#55ca92]">Technical resource hub</p><h1 className="mt-5 max-w-[10ch] font-[var(--font-display)] text-[clamp(4rem,8vw,8rem)] font-extrabold uppercase leading-[0.79] tracking-[-0.055em]">Documents made useful for project teams.</h1></div><p className="max-w-lg text-[1rem] leading-7 text-white/67">What technical documents can you request from TEC? Use this hub to choose the most relevant product, guide or review path. Attach project context so TEC can route the request meaningfully.</p></div></section>
    <section className="section-space"><div className="container-xl"><div className="grid gap-px border border-[#c7d1d6] bg-[#c7d1d6] md:grid-cols-2">{RESOURCES.map((resource) => { const Icon = resource.icon; return <article key={resource.number} className="group flex min-h-[20rem] flex-col bg-white p-[clamp(1.6rem,4vw,3.25rem)] transition-colors hover:bg-[#0f171f]"><div className="flex items-start justify-between"><span className="font-[var(--font-mono)] text-[0.62rem] text-[#2fae78]">{resource.number}</span><Icon size={22} className="text-[#607384] transition-colors group-hover:text-[#55ca92]" /></div><div className="mt-auto"><h2 className="font-[var(--font-display)] text-[clamp(2.5rem,4vw,4rem)] font-bold uppercase leading-[0.83] tracking-[-0.035em] text-[#1a2834] transition-colors group-hover:text-white">{resource.title}</h2><p className="mt-4 max-w-md text-sm leading-6 text-[#607384] transition-colors group-hover:text-white/65">{resource.body}</p><Link href={resource.href} className="mt-7 inline-flex items-center gap-2 font-[var(--font-mono)] text-[0.64rem] font-medium uppercase tracking-[0.1em] text-[#1a2834] transition-colors group-hover:text-[#55ca92]">{resource.action}<ArrowUpRight size={15} /></Link></div></article>; })}</div></div></section>
    <section className="bg-[#173c36] py-8 text-white"><div className="container-xl flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="font-[var(--font-mono)] text-[0.62rem] uppercase tracking-[0.13em] text-[#55ca92]">Document request principle</p><h2 className="mt-2 font-[var(--font-display)] text-[2rem] font-bold uppercase leading-[0.9]">The best document request starts with the operating context.</h2></div><Link href="/contact?resource=documents" className="btn-secondary shrink-0">Start a document request <ArrowUpRight size={16} /></Link></div></section>
  </div>;
}
