import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, FileText, SearchCheck, ShieldCheck } from 'lucide-react';

/* TEC QUALITY — Bold Industrial / Evidence-led. */

export const metadata: Metadata = { title: 'Quality & Technical Documentation — TEC INDUSTRIES', description: 'Request current product documentation, project-specific technical support and applicable quality information from TEC INDUSTRIES for industrial piping discussions.', alternates: { canonical: '/quality' } };

const ROUTES = [
  { number: '01', title: 'Product Family', body: 'Start with the pipe, fitting, valve, support or machinery family relevant to your project.', icon: FileText },
  { number: '02', title: 'Operating Context', body: 'Share the application, line size, operating requirement and project location to make the request useful.', icon: SearchCheck },
  { number: '03', title: 'Current Documents', body: 'TEC can route the enquiry toward the current technical literature and project-support discussion.', icon: ShieldCheck },
];

export default function QualityPage() {
  return <div className="min-h-screen bg-[#f3f5f2]"><section className="relative overflow-hidden bg-[#090f14] text-white"><div className="absolute inset-y-0 right-0 hidden w-[55%] lg:block"><Image src="https://files.manuscdn.com/user_upload_by_module/session_file/310519663160765145/tKtWtaVZIbBGUHWC.jpg" alt="Industrial pipe material detail" fill sizes="55vw" className="object-cover opacity-55" /><div className="absolute inset-0 bg-[linear-gradient(90deg,#090f14_0%,rgba(9,15,20,0.72)_44%,rgba(9,15,20,0.18)_100%)]" /></div><div className="absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(85,202,146,0.1)_1px,transparent_1px),linear-gradient(90deg,rgba(85,202,146,0.1)_1px,transparent_1px)] [background-size:56px_56px]" /><div className="container-xl relative z-10 py-[clamp(5rem,10vw,9rem)]"><div className="max-w-3xl"><p className="section-eyebrow text-[#55ca92]">Technical confidence</p><h1 className="mt-5 max-w-[10ch] font-[var(--font-display)] text-[clamp(4rem,8vw,8rem)] font-extrabold uppercase leading-[0.79] tracking-[-0.055em]">Evidence before assumptions.</h1><p className="mt-7 max-w-xl text-[1rem] leading-7 text-white/67">What quality information should an industrial piping team request? Start with the correct product family and operating context. TEC can then direct your enquiry to applicable current documentation and a relevant project discussion.</p><Link href="/contact?resource=quality-documents" className="btn-primary mt-8">Request current documents <ArrowUpRight size={16} /></Link></div></div></section>
    <section className="section-space bg-white"><div className="container-xl"><div className="max-w-2xl"><p className="section-eyebrow">Request route</p><h2 className="section-heading">A clearer way to begin technical review.</h2></div><div className="mt-10 grid gap-px border border-[#c7d1d6] bg-[#c7d1d6] md:grid-cols-3">{ROUTES.map((route) => { const Icon = route.icon; return <article key={route.number} className="min-h-[20rem] bg-white p-7"><div className="flex justify-between"><span className="font-[var(--font-mono)] text-[0.62rem] text-[#2fae78]">{route.number}</span><Icon size={22} className="text-[#607384]" /></div><h2 className="mt-16 font-[var(--font-display)] text-[2.6rem] font-bold uppercase leading-[0.84] tracking-[-0.035em] text-[#1a2834]">{route.title}</h2><p className="mt-4 text-sm leading-6 text-[#607384]">{route.body}</p></article>; })}</div></div></section>
    <section className="bg-[#0f171f] py-[clamp(4rem,7vw,7rem)] text-white"><div className="container-xl grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="section-eyebrow text-[#55ca92]">Quality questions</p><h2 className="max-w-[12ch] font-[var(--font-display)] text-[clamp(3rem,5vw,5.25rem)] font-extrabold uppercase leading-[0.82] tracking-[-0.045em]">Bring the requirement. Ask for the current document.</h2><p className="mt-6 max-w-xl text-[0.98rem] leading-7 text-white/66">For a useful request, include the product family, intended application, nominal size, operating conditions, quantity and project location. This avoids generic document handoffs and helps TEC respond in the right context.</p></div><Link href="/resources" className="btn-secondary">Explore technical resources <ArrowUpRight size={16} /></Link></div></section></div>;
}
