import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';

/* TEC PRODUCT INDEX — Bold Industrial / International-grade. */

export const metadata: Metadata = { title: 'Products — PPR, HDPE, Electrofusion, Valves & Pipe Support Systems', description: 'Explore TEC INDUSTRIES product systems for industrial piping projects, including PPR, HDPE, electrofusion fittings, industrial valves, supports and fusion machinery.', alternates: { canonical: '/products' } };

const PRODUCTS = [
  { name: 'PPR Pipe & Fittings', label: 'Pipe + fitting system', desc: 'Green and blue triple-layer PPR pipe systems with coordinated fitting-family and project-document conversations.', img: '/assets/ppr-pipes.png', href: '/products/ppr' },
  { name: 'HDPE Pipe & Fittings', label: 'Industrial pipe system', desc: 'HDPE pipe and fitting families for industrial and project-routing discussions.', img: '/assets/hdpe-pipes.png', href: '/products/hdpe' },
  { name: 'Electrofusion Fittings', label: 'Connection system', desc: 'Electrofusion fitting families for project teams planning pipe connections and branch interfaces.', img: '/assets/electrofusion.png', href: '/products/electrofusion' },
  { name: 'Industrial Valves', label: 'Flow-control components', desc: 'Valve families for industrial piping system and flow-control discussions.', img: '/assets/valves.png', href: '/products/valves' },
  { name: 'Pipe Support Systems', label: 'Installation support', desc: 'Hangers, brackets, clamps and support families for routing and installation planning.', img: '/assets/pipe-support.png', href: '/products/pipe-support' },
  { name: 'Fusion Machinery', label: 'Joining equipment', desc: 'PPR fusion welding machinery for coordinated system and installation conversations.', img: '/assets/fusion-machine.png', href: '/products/fusion-machine' },
  { name: 'Cooling Towers', label: 'Industrial cooling', desc: 'Cooling-tower options for industrial project discussions and utility planning.', img: '/assets/cooling-tower.png', href: '/products/cooling-tower' },
];

export default function ProductsPage() {
  return <div className="min-h-screen bg-[#f3f5f2]">
    <section className="relative overflow-hidden bg-[#090f14] text-white"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(85,202,146,0.1)_1px,transparent_1px),linear-gradient(90deg,rgba(85,202,146,0.1)_1px,transparent_1px)] [background-size:56px_56px]" /><div className="container-xl relative z-10 grid gap-10 py-[clamp(5rem,10vw,9rem)] lg:grid-cols-[1fr_0.8fr] lg:items-end"><div><p className="section-eyebrow text-[#55ca92]">Product system index</p><h1 className="mt-5 max-w-[10ch] font-[var(--font-display)] text-[clamp(4rem,8vw,8rem)] font-extrabold uppercase leading-[0.79] tracking-[-0.055em]">Designed for the full industrial conversation.</h1></div><p className="max-w-lg text-[1rem] leading-7 text-white/67">What does TEC INDUSTRIES supply? Explore the product families used in industrial piping, utility and project discussions. Select a system, then request the current details that relate to your application.</p></div></section>
    <section className="section-space"><div className="container-xl"><div className="grid gap-px border border-[#c7d1d6] bg-[#c7d1d6]">{PRODUCTS.map((product, index) => <Link href={product.href} key={product.href} className="group grid min-h-[22rem] bg-white md:grid-cols-[0.85fr_1.15fr] even:md:[&>div:first-child]:order-2 hover:bg-[#0f171f]"><div className="relative min-h-[16rem] overflow-hidden bg-[#0f171f]"><Image src={product.img} alt={product.name} fill sizes="(min-width: 768px) 36vw, 100vw" className="object-cover transition-transform duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(9,15,20,0.1),rgba(9,15,20,0.55))]" /></div><div className="flex flex-col p-[clamp(1.6rem,4vw,4rem)]"><span className="font-[var(--font-mono)] text-[0.62rem] uppercase tracking-[0.12em] text-[#2fae78]">{String(index + 1).padStart(2, '0')} · {product.label}</span><div className="mt-auto"><h2 className="mt-12 font-[var(--font-display)] text-[clamp(2.8rem,5vw,5rem)] font-bold uppercase leading-[0.8] tracking-[-0.04em] text-[#1a2834] transition-colors group-hover:text-white">{product.name}</h2><p className="mt-5 max-w-xl text-sm leading-6 text-[#607384] transition-colors group-hover:text-white/65">{product.desc}</p><span className="mt-7 inline-flex items-center gap-2 font-[var(--font-mono)] text-[0.65rem] font-medium uppercase tracking-[0.1em] text-[#1a2834] transition-colors group-hover:text-[#55ca92]">Open system detail <ArrowUpRight size={15} /></span></div></div></Link>)}</div></div></section>
    <section className="bg-[#173c36] py-8 text-white"><div className="container-xl flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="font-[var(--font-mono)] text-[0.62rem] uppercase tracking-[0.13em] text-[#55ca92]">Project requirement</p><h2 className="mt-2 font-[var(--font-display)] text-[2rem] font-bold uppercase leading-[0.9]">Need help selecting the right product conversation?</h2></div><Link href="/contact" className="btn-secondary shrink-0">Start a project enquiry <ArrowUpRight size={16} /></Link></div></section>
  </div>;
}
