import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight, Building2, Factory, FlaskConical, Utensils, Wrench, Waves } from 'lucide-react';

/* TEC INDUSTRIES — Bold Industrial sector map. */

export const metadata: Metadata = { title: 'Industries Served — Industrial Piping Applications | TEC INDUSTRIES', description: 'TEC INDUSTRIES supports B2B industrial piping conversations for manufacturing, chemical and pharma, textile, food and beverage, engineering, contracting and plant-maintenance teams.', keywords: ['industrial piping applications', 'industrial piping solutions Gujarat', 'plant utility piping', 'PPR project enquiry'], alternates: { canonical: '/industries' } };

const INDUSTRIES = [
  { title: 'Manufacturing', label: 'Plant utility and project systems', body: 'For manufacturing plants and project teams organising utility routes, product-family requirements and technical document requests.', icon: Factory },
  { title: 'Chemical & Pharma', label: 'Process-context enquiry', body: 'For teams that need to start with the operating medium, project context and applicable document or product discussion.', icon: FlaskConical },
  { title: 'Textile & Engineering', label: 'Project-led piping review', body: 'For engineering companies, contractors and industrial sites coordinating pipe systems, fittings, supports and installation requirements.', icon: Wrench },
  { title: 'Food & Beverage', label: 'Utility and process conversation', body: 'For plant teams looking to share service, line size, operating context and delivery requirements before product review.', icon: Utensils },
  { title: 'MEP & Contracting', label: 'System coordination', body: 'For MEP and plumbing contractors managing specification, quantity, project location and technical-resource requests.', icon: Building2 },
  { title: 'Water & Utilities', label: 'Infrastructure discussions', body: 'For industrial utility, water-treatment and related project contexts where product family and documentation need to be aligned.', icon: Waves },
];

export default function IndustriesPage() {
  return <div className="min-h-screen bg-[#f3f5f2]"><section className="relative overflow-hidden bg-[#090f14] text-white"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(85,202,146,0.1)_1px,transparent_1px),linear-gradient(90deg,rgba(85,202,146,0.1)_1px,transparent_1px)] [background-size:56px_56px]" /><div className="container-xl relative z-10 grid gap-10 py-[clamp(5rem,10vw,9rem)] lg:grid-cols-[1fr_0.8fr] lg:items-end"><div><p className="section-eyebrow text-[#55ca92]">Application context</p><h1 className="mt-5 max-w-[10ch] font-[var(--font-display)] text-[clamp(4rem,8vw,8rem)] font-extrabold uppercase leading-[0.79] tracking-[-0.055em]">Industrial progress has more than one environment.</h1></div><p className="max-w-lg text-[1rem] leading-7 text-white/67">Which industries does TEC serve? TEC supports B2B project conversations wherever industrial piping systems, utility routing, fittings, technical documents and RFQ context need to come together.</p></div></section>
    <section className="section-space"><div className="container-xl"><div className="grid gap-px border border-[#c7d1d6] bg-[#c7d1d6] md:grid-cols-2 xl:grid-cols-3">{INDUSTRIES.map((industry, index) => { const Icon = industry.icon; return <article key={industry.title} className="group flex min-h-[23rem] flex-col bg-white p-7 transition-colors hover:bg-[#0f171f]"><div className="flex items-start justify-between"><span className="font-[var(--font-mono)] text-[0.62rem] text-[#2fae78]">{String(index + 1).padStart(2, '0')}</span><Icon size={23} className="text-[#607384] transition-colors group-hover:text-[#55ca92]" /></div><div className="mt-auto"><p className="font-[var(--font-mono)] text-[0.57rem] uppercase tracking-[0.12em] text-[#607384] transition-colors group-hover:text-[#55ca92]">{industry.label}</p><h2 className="mt-3 font-[var(--font-display)] text-[2.8rem] font-bold uppercase leading-[0.83] tracking-[-0.035em] text-[#1a2834] transition-colors group-hover:text-white">{industry.title}</h2><p className="mt-4 text-sm leading-6 text-[#607384] transition-colors group-hover:text-white/65">{industry.body}</p><Link href={`/contact?industry=${encodeURIComponent(industry.title)}`} className="mt-7 inline-flex items-center gap-2 font-[var(--font-mono)] text-[0.65rem] font-medium uppercase tracking-[0.1em] text-[#1a2834] transition-colors group-hover:text-[#55ca92]">Discuss this context <ArrowUpRight size={15} /></Link></div></article>; })}</div></div></section>
    <section className="bg-[#173c36] py-8 text-white"><div className="container-xl flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="font-[var(--font-mono)] text-[0.62rem] uppercase tracking-[0.13em] text-[#55ca92]">Project-start question</p><h2 className="mt-2 font-[var(--font-display)] text-[2rem] font-bold uppercase leading-[0.9]">What will the piping system need to support?</h2></div><Link href="/contact" className="btn-secondary shrink-0">Start an RFQ <ArrowUpRight size={16} /></Link></div></section></div>;
}
