import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight, FileText, Layers3, MessageSquareText } from 'lucide-react';

/* TEC PROJECT SUPPORT — Bold Industrial / Evidence-led. */

export const metadata: Metadata = { title: 'Project Support — Industrial Piping Enquiry Framework | TEC INDUSTRIES', description: 'Prepare an industrial piping project enquiry with TEC INDUSTRIES by sharing application, system family, size, operating requirements, quantity and location.', alternates: { canonical: '/case-studies' } };

const STEPS = [
  { number: '01', title: 'Define the project context', body: 'Identify the application, operating medium, site location and project stage so the request begins in the right environment.' },
  { number: '02', title: 'Select the system family', body: 'Start with the relevant pipe, fitting, valve, support or fusion-machinery family and describe the interfaces you are coordinating.' },
  { number: '03', title: 'Request current information', body: 'Share nominal size, operating requirement and approximate quantity to request the applicable project discussion and document route.' },
];

export default function CaseStudiesPage() {
  return <div className="min-h-screen bg-[#f3f5f2]"><section className="relative overflow-hidden bg-[#090f14] text-white"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(85,202,146,0.1)_1px,transparent_1px),linear-gradient(90deg,rgba(85,202,146,0.1)_1px,transparent_1px)] [background-size:56px_56px]" /><div className="container-xl relative z-10 grid gap-10 py-[clamp(5rem,10vw,9rem)] lg:grid-cols-[1fr_0.8fr] lg:items-end"><div><p className="section-eyebrow text-[#55ca92]">Project support</p><h1 className="mt-5 max-w-[10ch] font-[var(--font-display)] text-[clamp(4rem,8vw,8rem)] font-extrabold uppercase leading-[0.79] tracking-[-0.055em]">Turn project context into a useful next step.</h1></div><p className="max-w-lg text-[1rem] leading-7 text-white/67">TEC will publish project stories only where project facts, permissions and outcomes are verified. Until then, this route explains how an industrial team can prepare a more effective piping-system enquiry.</p></div></section>
    <section className="section-space bg-white"><div className="container-xl"><div className="max-w-2xl"><p className="section-eyebrow">Enquiry framework</p><h2 className="section-heading">A project is more than a product list.</h2><p className="mt-6 text-[0.98rem] leading-7 text-[#607384]">What information helps TEC review an industrial piping requirement? The three steps below align your technical, commercial and document requests before the first conversation.</p></div><div className="mt-10 grid gap-px border border-[#c7d1d6] bg-[#c7d1d6] md:grid-cols-3">{STEPS.map((step, index) => <article key={step.number} className="min-h-[22rem] bg-white p-7"><span className="font-[var(--font-mono)] text-[0.62rem] text-[#2fae78]">{step.number}</span><h2 className="mt-16 font-[var(--font-display)] text-[2.65rem] font-bold uppercase leading-[0.84] tracking-[-0.035em] text-[#1a2834]">{step.title}</h2><p className="mt-5 text-sm leading-6 text-[#607384]">{step.body}</p><span className="mt-7 block font-[var(--font-mono)] text-[0.58rem] uppercase tracking-[0.1em] text-[#607384]">Project step {index + 1} of 3</span></article>)}</div></div></section>
    <section className="bg-[#0f171f] py-[clamp(4rem,7vw,7rem)] text-white"><div className="container-xl grid gap-px border border-white/12 bg-white/12 md:grid-cols-3">{[[FileText, 'PPR catalogue', 'Browse pipe and fitting families before your discussion.', '/resources/ppr-catalog'], [Layers3, 'Product systems', 'Review the broader TEC product-system index.', '/products'], [MessageSquareText, 'Project enquiry', 'Share your requirement in a structured RFQ.', '/contact']].map(([Icon, title, body, href]) => { const ProjectIcon = Icon as typeof FileText; return <Link key={title as string} href={href as string} className="group min-h-[16rem] bg-[#0f171f] p-7 transition-colors hover:bg-[#173c36]"><ProjectIcon size={22} className="text-[#55ca92]" /><h2 className="mt-10 font-[var(--font-display)] text-[2.3rem] font-bold uppercase leading-[0.85]">{title as string}</h2><p className="mt-4 text-sm leading-6 text-white/62">{body as string}</p><span className="mt-6 inline-flex items-center gap-2 font-[var(--font-mono)] text-[0.63rem] uppercase tracking-[0.1em] text-[#55ca92]">Open route <ArrowUpRight size={15} /></span></Link>; })}</div></section>
  </div>;
}
